import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
// import { InstagramScraper } from "../components/instagram-scraper";
// import datanum from "../public/datanum.json";

export default function Home({ instagramScraper }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
          
        </h1>
<div>IGUSER: 
{instagramScraper &&
                instagramScraper.map((igscrap) => (
              <div >
                {igscrap.username}
                {igscrap.latestPosts.map((post) => (
                  <div>
{post.url}
                  </div>
                ))}
              </div>
                   
                ))}
</div>
{/* <div>
{datanum &&
                datanum.map((igscrap) => (
              <div >
                {igscrap['#debug']}
              </div>
                   
                ))}
</div> */}
        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
//const fs = require('fs');



export async function getStaticProps() {
  // Run API calls in parallel
  //const [items] = await Promise.all([InstagramScraper()]);
  let users = require('/public/datanum.json');
  // console.log(users[0].id)
  // const uzi =  await Promise.all([users]);
  // console.log(uzi.id)
  // const usersRepo = {
  //   getAll: () =>  uzi,
  //   getById: id =>  uzi.find(x => x.id.toString() === id.toString()),
  //   find: x =>  uzi.find(x)
  // };
  // const jsdata = JSON.stringify(users)

  return {
    props: {

      instagramScraper: users,
    },
    //revalidate: 1,
  };
}
