import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
// import { InstagramScraper } from "../components/instagram-scraper";
// import datanum from "../public/datanum.json";
const path = require("path");
const fs = require("fs").promises;
// const axios = require("axios");


export default function Home({ instagramScraper }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
          
        </h1>
<div>
{instagramScraper &&
                instagramScraper.map((igscrap) => (
              <div key={igscrap.id}>
                IGUSER: {igscrap.username}
                {/* <Image  src={igscrap.url} alt="Vercel Logo" width={100} height={100} /> */}
                <Image alt={igscrap.fullName} src={igscrap.profilePicUrl} height={200} width={200} />
                Followers: {igscrap.followersCount}
                Follows: {igscrap.followsCount}
                Posts: {igscrap.postsCount}
                igtvVideoCount: {igscrap.igtvVideoCount}
                Follows: {igscrap.followsCount}

                {igscrap.latestPosts.map((post) => (
                  <div key={post.id}>
{post.caption}
<Image alt={post.caption} src={post.displayUrl} height={200} width={200} />


                  </div>
                ))}
              </div>
                   
                ))}
</div>
{/* <div>
{datanum &&
                datanum.map((igscrap) => (
              <div >
                {igscrap['#debug']}
              </div>
                   
                ))}
</div> */}
        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
//const fs = require('fs');



export async function getStaticProps() {
  // Run API calls in parallel
  //const [items] = await Promise.all([InstagramScraper()]);
  // let users = require(path.join("datanum.json"));
  
  // const filePath = require("../public/datanum.json");
  // const filePath2 = require("../public/datanum2.json");
  const stateFile = "./public/datanum2.json";

  const readFile = "./public/datanum.json";

  // console.log('fifififi1: '+path.join(process.cwd(), 'public/datanum2.json'))
  const file_data = await fs.readFile(readFile)
  const json_data = JSON.parse(file_data)
  // console.log('fifififi2: '+file_data)
  const saveLastEventSequenceId = (sequenceId) => {
    try {
        

      fs.writeFileSync(stateFile, json_data);
      // console.log(json_data) 
      
    } catch (err) {
console.log(err)    }
  };
  // fs.writeFileSync(stateFile, filePath);
  console.log('SENDING FILE DONE~!')
  console.log(json_data)
  // const uzi =  await Promise.all([users]);
  // console.log(uzi.id)
  // const usersRepo = {
  //   getAll: () =>  uzi,
  //   getById: id =>  uzi.find(x => x.id.toString() === id.toString()),
  //   find: x =>  uzi.find(x)
  // };
  // const jsdata = JSON.stringify(users)

  return {
    props: {

      instagramScraper: json_data,
    },
    //revalidate: 1,
  };
}
